"""add user security fields

Revision ID: 0c148e1838b7
Revises:
Create Date: 2026-05-06 20:55:20.950507

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c148e1838b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "failed_login_count", sa.Integer(), nullable=False, server_default="0"
            )
        )
        batch_op.add_column(
            sa.Column("is_locked", sa.Boolean(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("locked_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("locked_at")
        batch_op.drop_column("is_locked")
        batch_op.drop_column("failed_login_count")
        batch_op.drop_column("last_login")

    # ### end Alembic commands ###
